[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chatbot-dataset-tools"
version = "0.7.1"
dependencies = [
    "pytest",
    "respx"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["chatbot_dataset_tools*"]